### ISSUE TITLE
Non-Functional Sign-Up Button; Need to Create a Sign-Up Page

### ISSUE THREAD

**Issue by myselfshivams** [arpittiwari24/YourNextSaas.online#13]
The sign-up button is currently non-functional, which prevents users from creating new accounts. To enhance user experience and facilitate account creation, we need to implement a dedicated sign-up page. This page should align with the current design and color scheme of the website.

Labels:
- GSSoC
- Hacktoberfest

@arpittiwari24 Please assign this issue to me(@myselfshivams).

**Comment by arpittiwari24** [comment]
Hey , can you please check if the issue already exists  :D
