### ISSUE TITLE
Add Missing Meta Tags, Robots.txt, and Sitemap for Improved SEO

### ISSUE THREAD

**Issue by myselfshivams** [arpittiwari24/YourNextSaas.online#20]
The website currently lacks essential SEO elements such as meta tags, robots.txt, and a sitemap. These are critical for optimizing the site’s visibility on search engines and improving overall discoverability.

Proposed Solution:
- Meta Tags: Add relevant meta tags (title, description, keywords, Open Graph, Twitter cards, etc.) to improve SEO and social sharing.
- Robots.txt: Create a robots.txt file to guide web crawlers and define which pages should be indexed.
- Sitemap: Generate an XML sitemap to ensure proper indexing by search engines.

Labels:
- gssoc
- hacktoberfest

@arpittiwari24 Please assign this task to me (myselfshivams).

**Comment by arpittiwari24** [comment]
Hey , thanks for noticing this issue . Assigning this to you .
