### ISSUE TITLE
Misalignment of the Fans Section

### ISSUE THREAD

**Issue by adityapandey23** [arpittiwari24/YourNextSaas.online#5]
![image](https://github.com/user-attachments/assets/ad1a3817-eeac-4d2a-9f94-31fb0eba1ef4)

The Fans sections seems to be a little bit off. Can you assign this issue to me so that I can fix it!

**Comment by arpittiwari24** [comment]
Yup sure . Assigning this .

**Comment by adityapandey23** [comment]
Hey @arpittiwari24 , I have created a pr #15 . You can check it! Also will this contribution be considered for Ggsoc-ext if so then can you please add the label ?
Thanks in advance!

**Comment by adityapandey23** [comment]
Hey @arpittiwari24 thanks for the letting me fix this. It would be really great if you could let me know whether this contribution will be counted in Ggsoc-ext ?
Thanks in advance!
Looking forward to make more contributions to this repo!
