### ISSUE TITLE
Enhancing UI of Cards and inquiry form

### ISSUE THREAD

**Issue by sezallagwal** [arpittiwari24/YourNextSaas.online#58]
![image](https://github.com/user-attachments/assets/e249ec43-7e37-4c6e-98e5-1ac2a3c87034)
I want to add hover effects to these pricing cards 

![image](https://github.com/user-attachments/assets/c433af0f-7e75-4ce5-89d8-2c5052c4be5a)
add outline to the input fields to make it look presentable 

Assign this to me under gssoc-ext and hacktoberfest

**Comment by iamrudhresh** [comment]
Hi,

I am participating in GSSoC'24 Extended, and I would like to work on this issue. Could you please assign it to me?

Thank you!
