### ISSUE TITLE
Env Variables fetch 

### ISSUE THREAD

**Issue by inkerton** [arpittiwari24/YourNextSaas.online#8]
Their is no description as to from where do I have to get these env variables.
```javascript
NEXTAUTH_URL =
NEXTAUTH_SECRET = 

SUPABASE_ANON_KEY = 
NEXT_PUBLIC_SUPABASE_URL =
NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY = 

GOOGLE_CLIENT_ID =
GOOGLE_CLIENT_SECRET =

LEMONSQUEEZY_STORE_ID = 
LEMONQUEEZY_API_KEY = 
LEMON_SQUEEZY_WEBHOOK_SIGNATURE = 

MONGO_URI = 

RESEND_API_KEY = 
```

Proper instructions needs to be given

**Comment by inkerton** [comment]
As i am getting the error 
![image](https://github.com/user-attachments/assets/6062dd18-745f-48ed-9b38-c71640a9a4d3)

**Comment by arpittiwari24** [comment]
Hey , this issue is caused due to no proper docs . Can you update the readme on how to get all these env variables ??

**Comment by inkerton** [comment]
Yes, can you assign it to me under gssoc-extnd or hacktoberfest. 
I will look into the issue an draft proper instruction on how to get each and every env variable.

**Comment by arpittiwari24** [comment]
Yup sure .

**Comment by inkerton** [comment]
@arpittiwari24 i have raised a PR do check it out and also add a level to the issue since it will be easier to get points.

**Comment by inkerton** [comment]
@arpittiwari24  Can you add appropriate level tag also to the issue so it would be easier for me to get my points.
